### ISSUE TITLE
custom ansible filter to allow `jq` filters

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/hgi-ansible#16]
It would be nice if we could use jq filters (https://stedolan.github.io/jq/manual/) for the more complex lookups that can often be very hack-ish using ansible's built-in filters. 

We could write a custom filter to pass the data through to pyjq: https://pypi.python.org/pypi/pyjq

**Comment by colin-nolan** [comment]
@jrandall: Ansible 2.2 introduces a new [`json_query` filter](http://docs.ansible.com/ansible/playbooks_filters.html#json-query-filter), based on [JMESPath](http://jmespath.org/examples.html). It's not `jq` but it looks like it would be just as good for complex lookups!
