### ISSUE TITLE
Restructuring of Terraform modules

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/hgi-ansible#53]
The directory structure of the Terraform modules is current rather unwieldy due to the organic way in which it has evolved; I'm finding it painful to identify the most up-to-date modules.

I would like to propose that we structure Terraform modules as such:
```
${service}/[${subService}/]${service}-[${subService}-]v${version}/
```
where `[]` denotes an optional part of the path as not all services will have sub-services.

e.g.
```
SSH Gateway:
ssh-gateway/ssh-gateway-v1/
ssh-gateway/ssh-gateway-v2/

Hail:
hail/compute/hail-compute-v1/
hail/compute/hail-compute-v2/
hail/master/hail-master-v1/

Arvados:
arvados/keep/arvados-keep-v1/
arvados/shell/arvados-shell-v1/
arvados/shell/arvados-shell-v2/
```

**Comment by jrandall** [comment]
If we must have annoying hierarchy all over the place, why not drop the repetition and just have `arvados/keep/v1` ?

What are your expectations about things like clusters that actually assemble a lot of different components together into a package? 

The longer term plan for this was supposed to be to actually refer to modules in an actual versioned way - i.e. in another repo that is tagged with a version.

**Comment by colin-nolan** [comment]
Resolved to: `${service}/v${version}/[${subService}/]`
